### ISSUE TITLE
Data set download

### ISSUE THREAD

**Issue by 1741653267** [QinggangSUN/keras_multiple_target_recognition#1]
It is very difficult to find the data set download link

**Comment by QinggangSUN** [comment]
The official website of the shipsEar database is https://atlanttic.uvigo.es/underwaternoise/ . Users may contact the author David Santos Domínguez through email dsantos@gts.uvigo.es to get the database.

**Comment by Vanillaholic** [comment]
Have you got the Dataset? I sent email to the author but there is no reply @QinggangSUN @1741653267
